### ISSUE TITLE
Duplication of effort?

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [Rusty-Quartz/Quartz#3]
Heya, I am not familiar with Rust but if you aren't aware of [Feather](https://github.com/feather-rs/feather) already, maybe looking into it is a good idea? As it's another Minecraft implementation in Rust and looks pretty neat

**Comment by maddymakesgames** [comment]
Okay late response, but this is something I think is important to semi-formalize.
We are aware of a bunch of other projects very similar to this.

The reason we are not helping any other projects, aside from just wanting to have our own project, is due to us having separate goals.
The main goals of this project are to have a custom minecraft server implementation that is one to one compatible with vanilla while being able to keep up with the latest vanilla.
This is not necessarily feasible, but this is the ideal.
The more practical goal is to be as close to one to one with vanilla while generally optimizing speed and ease of development.

We also follow different practices, unlike Feather we are not following a clean-room protocol. For example, I have been decompiling and looking at minecraft code for help with implementations and debugging.

Overall we started this because we just wanted to make our own server, but as we decided the goals of the project, this is what we've informally come to so far.
